#=========================================================#
#                 Database configuration                  #
#=========================================================#

MONGODB:
  DATABASE: "punishments"
  HOST: "127.0.0.1"
  PORT: 27017
  AUTH:
    ENABLED: true
    USER: "Nature"
    PASSWORD: "Kurac"

#=========================================================#
#                Punishments configuration                #
#=========================================================#

# Requires Bungee plugin addon
# LINK
# Global punishments, messages
BUNGEE: false

SERVER_NAME: "Server"

# Should we ip ban when banning?
IP_BAN: false

# Should the IP command be executable by console only?
IP_COMMAND_CONSOLE_ONLY: false

# Should we show banned alts when player joins the server?
SHOW_BANNED_ALTS: true