#=========================================================#
#                 Database configuration                  #
#=========================================================#

# This is required in order for the plugin to work.
MONGODB:
  DATABASE: "punishments"
  HOST: "127.0.0.1"
  PORT: 27017
  AUTH:
    ENABLED: false
    USER: ""
    PASSWORD: ""

# This is only required for bungee mode due to synchronization through the whole network.
REDIS:
  CHANNEL: "punishments"
  HOST: "127.0.0.1"
  PORT: 6379
  AUTH:
    ENABLED: false
    PASSWORD: ""

#=========================================================#
#                Punishments configuration                #
#=========================================================#

# Requires redis database
# Global punishments, messages...
BUNGEE: false

# Server name used when punishing a player.
SERVER_NAME: "Server"

# Should we ip ban when banning?
IP_BAN: false

# Should the IP command be executable by console only?
IP_COMMAND_CONSOLE_ONLY: false

# Should we show banned alts when player joins the server?
SHOW_BANNED_ALTS: true

# Weight
# EXAMPLE: Players with weight 10 wont be able to ban a player with weight 20.
WEIGHT:
  10: "punish.weight.10"
  20: "punish.weight.20"
  30: "punish.weight.30"

DEFAULT:
  OP: 999
  CONSOLE: 1000